# Generated by Django 4.2.16 on 2025-01-04 15:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_course_featured_img_course_techs"),
    ]

    operations = [
        migrations.CreateModel(
            name="St_Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "file",
                    models.FileField(
                        upload_to="student_assignment/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["txt", "doc", "docx", "pdf"]
                            )
                        ],
                    ),
                ),
                ("uploaded_At", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="course_assignment/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["txt", "doc", "docx", "pdf"]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment",
                        to="main.course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "4 . Assignments",
            },
        ),
    ]
