# Generated by Django 4.2.16 on 2025-01-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_st_assignment_assignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='st_assignment',
            options={'verbose_name_plural': '5 .Similarity Checker Assignments'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '6 . Student'},
        ),
    ]
