# Generated by Django 4.2.16 on 2025-01-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_st_assignment_options_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='default_username', max_length=100),
        ),
    ]
