# Generated by Django 4.2.16 on 2025-01-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qualification',
        ),
    ]
