# Generated by Django 4.2.16 on 2025-01-06 10:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcourseenrollment',
            options={'verbose_name_plural': '8. Enrolled Courses'},
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_file', models.FileField(upload_to='assignment_submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'doc', 'docx', 'pdf'])])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
            options={
                'verbose_name_plural': 'Assignment Submissions',
                'unique_together': {('student', 'assignment')},
            },
        ),
    ]
