# Generated by Django 4.2.16 on 2025-01-06 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_assignment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentcourseenrollment",
            options={"verbose_name_plural": "8. Enrolled Courses"},
        ),
    ]
