# Generated by Django 4.2.16 on 2025-01-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_studentcourseenrollment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
    ]
