# Generated by Django 4.2.16 on 2025-02-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_studentcourseenrollment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='username',
            field=models.CharField(default='default_username', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
