# Generated by Django 4.2.16 on 2025-02-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_key',
            field=models.CharField(default='DEFAULT_KEY', max_length=50),
            preserve_default=False,
        ),
    ]
