# Generated by Django 4.2.16 on 2025-02-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_course_enrollment_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
