# Generated by Django 4.2.16 on 2025-02-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_lecturer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='username',
        ),
    ]
