# Generated by Django 4.2.16 on 2025-02-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_lecturer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='featured_img',
            field=models.ImageField(upload_to='course_imgs/'),
        ),
    ]
