# Generated by Django 4.2.16 on 2025-02-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_course_featured_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='featured_img',
            field=models.ImageField(upload_to='course_imgs/'),
        ),
    ]
