# Generated by Django 4.2.16 on 2025-03-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_lecturer_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='Untitled Assignment', max_length=200),
        ),
    ]
